### PR TITLE
Fix #11555 : Message display on adherent public

### LINKED ISSUE #11555: Extrafields: no message displayed if a required extrafield is missing in the members autosubscription formular
# Bug
When validating the members autosubscription formular (public/members/new.php) with missing required extrafields, no message is displayed, the formular is not validated (back to top of page) but a subscription request email is sent.

## Environment
- **Version**: 10.0.0
- **Web server**: Apache

## Expected and actual behavior
The autosubscription formular (public/members/new.php) does not have the same behavior for required Dolibarr standard fields and for the extrafields concerning the error messages: when a required Dolibarr standard field is missing, a message is displayed in red but when a required extrafield is missing, no error message is displayed but the formular is back to top, the data are not validated but a subscription request is sent by email.
It is necessary to show an error message the same way as the standard Dolibarr fields if a required extrafield is missng. No email should be sent until the data are not validated and saved in the database.

## Steps to reproduce the behavior
Use the standard autosubscription formular ((public/members/new.php) with mandatory extrafields.

### PR DESCRIPTION
**Pull request by Hystepik**
Fix an error where object was trying to be created when a required extrafields was not set and there was no messages for the required empty extrafield

### CODE REVIEW

File: htdocs/public/members/new.php [hunk 1]
```diff
@@ -469,6 +471,7 @@ function llxFooterVierge()
 print '</div>';
 
 dol_htmloutput_errors($errmsg);
+dol_htmloutput_events();
```
Comment (eldy) [inline htdocs/public/members/new.php:474]: If we add dol_htmloutput_events(), do we still need dol_htmloutput_errors() ?
