### PR TITLE
FIX #4756

### LINKED ISSUE #4756: Bug: PostgreSQL error when installing Dolibarr
# Bug

```
Creación de funciones
Request 610 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_advtargetemailing FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();    Error de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_advtargetemailing" does not exist LOCATION: RangeVarGetRelidExtended, namespace.c:418
Creación de funciones
Request 610 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_ecm_documents FOR EACH ROW EXECUTE PROCEDURE update_modified_column_date_u(); Error de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_ecm_documents" does not exist LOCATION: RangeVarGetRelidExtended, namespace.c:418
Creación de funciones
Request 610 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_printer_ipp FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();  Error de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_printer_ipp" does not exist LOCATION: RangeVarGetRelidExtended, namespace.c:418
Creación de funciones
Request 610 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_time_basket FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();  Error de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_time_basket" does not exist LOCATION: RangeVarGetRelidExtended, namespace.c:418
Creación de funciones
Request 610 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_timebasket_counter FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();   Error de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_timebasket_counter" does not exist LOCATION: RangeVarGetRelidExtended, namespace.c:418
```
## Environment
- **Version**: 3.8.4
- **PHP**: 5.6.19-1+deb.sury.org~trusty+1
- **Database**:     9.3.11
- **URL(s)**: http://dolibarr.local/install/step2.php

### PR DESCRIPTION
**Pull request by ghost**
FIX #4756

### CODE REVIEW

File: htdocs/install/pgsql/functions/functions.sql [hunk 1]
```diff
@@ -96,7 +95,7 @@ CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_cronjob FOR EACH ROW
 CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_deplacement FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();
 CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_don FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();
 CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_don_extrafields FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();
-CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_ecm_documents FOR EACH ROW EXECUTE PROCEDURE update_modified_column_date_u();
+CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_ecm_directory FOR EACH ROW EXECUTE PROCEDURE update_modified_column_date_u();
```
Comment (eldy) [inline htdocs/install/pgsql/functions/functions.sql]: Table seems to be llx_ecm_directories and  not llx_ecm_directory

**Comment by ghost** [comment]
@eldy, true, fix
