### PR TITLE
fix Users list filter by gender

### LINKED ISSUE #15557: Filter by gender in Users list don't work correctly
# Bug
Filter by gender in Users list don't work correctly

## Environment
- **Version**: 13.0.0-beta
- **OS**: Linux srv-claix-debian 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
- **Web server**: Apache/2.4.38 (Debian)
- **PHP**: 7.3.19-1~deb10u1
- **Database**: MySQL or MariaDB 5.5.5-10.3.25-MariaDB-0+deb10u1
- **URL(s)**: /projet/list.php?leftmenu=projets
Select 

## Steps to reproduce the behavior
Open config->users list.
Add gender column.
Filter only females : OK
Filter only male: BUG it shows both (not other and null)

### PR DESCRIPTION
**Pull request by StephaneLesage**
# Fix #15557 

Search request construction has been modified to use natural_search.
But searching LIKE "%man%" also include "woman"...

### CODE REVIEW

File: htdocs/user/list.php [hunk 1]
```diff
@@ -343,7 +343,7 @@
 if ($search_login != '')      $sql .= natural_search("u.login", $search_login);
 if ($search_lastname != '')   $sql .= natural_search("u.lastname", $search_lastname);
 if ($search_firstname != '')  $sql .= natural_search("u.firstname", $search_firstname);
-if ($search_gender != '' && $search_gender != '-1')     $sql .= natural_search("u.gender", $search_gender);
+if ($search_gender != '' && $search_gender != '-1')     $sql .= " AND u.gender = '".$search_gender."'";	// Cannot use natural_search as looking for %man% also includes woman
```
Comment (frederic34) [inline htdocs/user/list.php:346]: @StephaneLesage add $db->escape

Comment (StephaneLesage) [reply htdocs/user/list.php]: right.
Code in v12 is missing it also.
