### PR TITLE
FIX #22883

### LINKED ISSUE #22883: SQL syntax error at Income/Expense reporting module
### Bug

We have just moved to MySQL 8.0.30 recently. And MySQL 8.0.30 is more strict in nature than its previous one. At the file **/data/dolibarr-development** there is wrong SQL code. Which is given below.
` $sql .= " FROM ".MAIN_DB_PREFIX."accounting_bookkeeping as f";
 296         $sql .= ", ".MAIN_DB_PREFIX."accounting_account as aa";
 297         $sql .= " WHERE f.numero_compte = aa.account_number";
 298         $sql .= " AND ".$predefinedgroupwhere;
 299         $sql .= " AND fk_pcg_version = '".$db->escape($charofaccountstring)."'";
 300         $sql .= " AND f.entity = ".$conf->entity;
 301         if (!empty($date_start) && !empty($date_end)) {
 302                 $sql .= " AND f.doc_date >= '".$db->idate($date_start)."' AND f.doc_date <= '".$db->idate($date_end)."'";
 303         }
 304         $sql .= " GROUP BY pcg_type DESC";
`

The correct SQL code should be like below
` $sql .= " FROM ".MAIN_DB_PREFIX."accounting_bookkeeping as f";
 296         $sql .= ", ".MAIN_DB_PREFIX."accounting_account as aa";
 297         $sql .= " WHERE f.numero_compte = aa.account_number";
 298         $sql .= " AND ".$predefinedgroupwhere;
 299         $sql .= " AND fk_pcg_version = '".$db->escape($charofaccountstring)."'";
 300         $sql .= " AND f.entity = ".$conf->entity;
 301         if (!empty($date_start) && !empty($date_end)) {
 302                 $sql .= " AND f.doc_date >= '".$db->idate($date_start)."' AND f.doc_date <= '".$db->idate($date_end)."'";
 303         }
 304         $sql .= " GROUP BY pcg_type ORDER BY pcg_type DESC";
`

### Environment Version

16.0.1

### Environment OS

AlmaLinux 8.6

### Environment Web server

Apache 2.4.37

### Environment PHP

8.1.12

### Environment Database

MySQL 8.0.30

### Environment URL(s)

https://HOST/compta/resultat/clientfourn.php?leftmenu=accountancy_report

### Expected and actual behavior

There should not be any MySQL query error.

### Steps to reproduce the behavior

Just login to Dolibarr as admin. The Dolibarr installation must has accounting module enabled. Then access the following path.

Accounting --> Reporting --> Income / Expense --> By predefined groups

### Attached files

MysQL-Bug

### PR DESCRIPTION
**Pull request by alsoft10**
[#22883](https://github.com/Dolibarr/dolibarr/issues/22883) Strict SQL syntax fixed for MySQL server version 8.0.30.

### CODE REVIEW

**Comment by alsoft10** [comment]
@eldy fixed MySQL query syntax error.

File: htdocs/compta/resultat/clientfourn.php [hunk 1]
```diff
@@ -301,7 +301,7 @@
 	if (!empty($date_start) && !empty($date_end)) {
 		$sql .= " AND f.doc_date >= '".$db->idate($date_start)."' AND f.doc_date <= '".$db->idate($date_end)."'";
 	}
-	$sql .= " GROUP BY pcg_type DESC";
```
Comment (eldy) [inline htdocs/compta/resultat/clientfourn.php:304]: I think we must just remove the DESC because the order by is inserted 2 lines later...

Comment (alsoft10) [reply htdocs/compta/resultat/clientfourn.php:304]: @eldy you are correct. But the query is not generating correctly that's why MySQL 8.0.30 showing error. Okay I am fixing the code further.
