### PR TITLE
FIX #4926

### LINKED ISSUE #4926: Error on instalation dolibarr 3.9.0 in postgresql
Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_advtargetemailing FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();    Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_advtargetemailing" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_askpricesupplier FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();     Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_askpricesupplier" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_askpricesupplier_extrafields FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();     Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_askpricesupplier_extrafields" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_askpricesupplierdet_extrafields FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();  Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_askpricesupplierdet_extrafields" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_ecm_documents FOR EACH ROW EXECUTE PROCEDURE update_modified_column_date_u();     Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_ecm_documents" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_printer_ipp FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();  Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_printer_ipp" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_time_basket FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();  Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_time_basket" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

Creat Functions
Request 648 : CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_timebasket_counter FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();   Erro de SQL DB_ERROR_NOSUCHTABLE ERROR: 42P01: relation "llx_timebasket_counter" does not exist LOCATION: RangeVarGetRelidExtended, src\backend\catalog\namespace.c:418

### PR DESCRIPTION
**Pull request by ghost**
FIX #4926

### CODE REVIEW

File: htdocs/install/pgsql/functions/functions.sql [hunk 1]
```diff
@@ -96,7 +92,7 @@ CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_cronjob FOR EACH ROW
 CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_deplacement FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();
 CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_don FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();
 CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_don_extrafields FOR EACH ROW EXECUTE PROCEDURE update_modified_column_tms();
-CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_ecm_documents FOR EACH ROW EXECUTE PROCEDURE update_modified_column_date_u();
+CREATE TRIGGER update_customer_modtime BEFORE UPDATE ON llx_ecm_directory FOR EACH ROW EXECUTE PROCEDURE update_modified_column_date_u();
```
Comment (eldy) [inline htdocs/install/pgsql/functions/functions.sql]: Table seems to be llx_ecm_directories not llx_ecm_directory
