### PR TITLE
Fix #22494 Bad error message and trans missing (radio button)

### LINKED ISSUE #22494: Radio button empty value gives ErrorBadValueForParamNotAString
### Bug

I try to make a Radio button in "Attributs supplémentaries (commandes)" but when there is no value chosen this message appear: "ErrorBadValueForParamNotAString"

### Environment Version

16

### Environment OS

Debian 11

### Environment Web server

Apache

### Environment PHP

7.4.30

### Environment Database

Maria 10.5.15

### Environment URL(s)

_No response_

### Expected and actual behavior

When making a Radio button list in "Attributs supplémentaries (commandes)" it is not possible to leave an empty value as it gives the message "ErrorBadValueForParamNotAString" both in the listing and on the card, as can bee seen on the 2 attached images.

I assume it should be possible to leave an empty value?

The Radio button list looks like this

1,Reçu
2,Confirmé
3,Refusé

I've temporarly solved it by checking Required and added one more row like this

1,Pas d'réponse
2,Reçu
3,Confirmé
4,Refusé

### Steps to reproduce the behavior

_No response_

### Attached files

listing
card

### PR DESCRIPTION
**Pull request by ibuiv**
# Fix #22494 Bad error message and trans missing (radio button)

On commande/card if an radio button extrafield has a bad default value (or none), the displayed error message was "ErrorBadValueForParamNotAString"
It is now the translation for "ErrorNoValueForRadioType" (Example : Les valeurs de la liste d'options doivent être renseignées in French version)

### CODE REVIEW

File: htdocs/commande/card.php [hunk 1]
```diff
@@ -60,7 +61,7 @@
 }
 
 // Load translation files required by the page
-$langs->loadLangs(array('orders', 'sendings', 'companies', 'bills', 'propal', 'deliveries', 'products', 'other'));
+$langs->loadLangs(array('orders', 'sendings', 'companies', 'bills', 'propal', 'deliveries', 'products', 'other', 'errors'));
```
Comment (eldy) [inline htdocs/commande/card.php:64]: The goal of the errors lang file is to contains error message that are loaded only when required.
Can you move the load of lang file
$langs->load("errors");
just before the code that need the error keys, so before the line 
$value = $langs->trans('ErrorNoValueForRadioType');

Comment (ibuiv) [reply htdocs/commande/card.php]: ok done
