### PR TITLE
Close #20930 NEW Use ajax for state loading after country change

### LINKED ISSUE #20930: User card : state not related to country
### Bug

While creating or editing a user card, the state dropdown field is not refreshed after selecting a country. All states from all countries are available.
On thirdparty card there's a refresh after country selection

### Environment Version

at least 13.0

### Environment OS

all

### Environment Web server

all

### Environment PHP

all

### Environment Database

all

### Environment URL(s)

http://dolibarr.local/user/card.php?leftmenu=users&action=create

### Expected and actual behavior

The state dropdown should refresh to show only states related to the selected country

### Steps to reproduce the behavior

Go on the user creation form, select a country in the list, check the state dropdown content

### Attached files

image

### PR DESCRIPTION
**Pull request by homer8173**
combo country / state

### CODE REVIEW

**Comment by homer8173** [comment]
isn't it time to implement it ?

File: htdocs/core/ajax/ziptown.php [hunk 1]
```diff
@@ -141,6 +141,9 @@
 	}
 
 	echo json_encode($return_arr);
+} elseif (isset($_GET['country_codeid'])) {
```
Comment (eldy) [inline htdocs/core/ajax/ziptown.php:144]: Must use here GETPOSTISSET
