### PR TITLE
FIX the member e-mail on resign and validation.

### LINKED ISSUE #9640: email module Adhérents
# Bug
email feature does not work anymore properly.

_Échec de l'envoi de l'email (émetteur=xyz@123.com, destinataire=xyz@gmail.com). Failed to send mail with smtps lib to HOST=, PORT=465
Constructor of object CMailFile was not initialized without errors._

## Environment
- **Version**: 8.0.2

## Expected and actual behavior
When sending an email or activating /de-activating an "Adhérent", an error message appears and email not send. This is since version 8.0.0

### PR DESCRIPTION
**Pull request by laudeco**
# Fix #9640

The problem is due to the new configuration of the module members. Indeed in the previous version the subject and the content of the e-mail were directly written in the module itself and saved in global variables.

In the new version this configuration has been replaced by the usage of e-mail templates (it's a very great idea) but it introduces a  backward compatibility break. Because if you do not change your configuration, the module doesn't send e-mails anymore.

My fix introduces a fallback on the previous configuration.

Of course this fix needs to be removed in a future version, but I'm not yet sure of the best ay to do this, I propose to discuss about that in the ticket #9640.

### CODE REVIEW

File: htdocs/adherents/card.php [hunk 1]
```diff
@@ -634,6 +634,12 @@
 					$msg     = $arraydefaultmessage->content;
 				}
 
+                if (empty($labeltouse)) {
+                    //fallback on the old configuration.
```
Comment (eldy) [inline htdocs/adherents/card.php:638]: I think a warning with
setEventMessages('Error setup of module Member not complete....
would be better to ask user to finish the migration that can not be done automatically.

Comment (laudeco) [reply htdocs/adherents/card.php:638]: Ok do I keep the fallback too ?

Comment (eldy) [reply htdocs/adherents/card.php:638]: I prefer warning only so user will be forced to fix its setup. That's what we want with v8, to have a setup complete before using it.

Comment (laudeco) [reply htdocs/adherents/card.php:638]: I put an error message since the action cannot continue.
For me  : 
* Success when the requested action has been done.
* Warning when something is wrong but the system accomplished the action 
* Error when the action cannot be performed.
