### PR TITLE
25828 odt fix wrong styles

### LINKED ISSUE #25828: odt Generator Problem wrong colors and styles
### Bug

When generating odt it happens wrong and mixed styles and colors when using html code.

To Fix this we need to change line 299 ff.

from $key = floatval(str_replace('.', '', microtime(true))) + rand(0, 10);

$key = str_replace('.', '', microtime(true)) . uniqid() . rand(0, 10); // fixed by tronx2100 

now it will work perfect without errors.

### Environment Version

18.0.1

### Environment OS

linux debian bookworm

### Environment Web server

nginx

### Environment PHP

8.2.7

### Environment Database

_No response_

### Environment URL(s)

_No response_

### Expected and actual behavior

_No response_

### Steps to reproduce the behavior

_No response_

### Attached files

_No response_

### PR DESCRIPTION
**Pull request by a-schild**
# FIX #25828 wrong style numbering
With php 8.2 and very very fast cpu's, we can still have non-unique styles
Adding a guuid solves this

### CODE REVIEW

File: htdocs/includes/odtphp/odf.php [hunk 1]
```diff
@@ -304,7 +304,7 @@ private function _replaceHtmlWithOdtTag($tags, &$customStyles, &$fontDeclaration
 							}
 							if (strlen($odtStyles) > 0) {
 								// Generate a unique id for the style (using microtime and random because some CPUs are really fast...)
-								$key = floatval(str_replace('.', '', microtime(true))) + rand(0, 10);
+								$key = str_replace('.', '', microtime(true)) . uniqid() . rand(0, 10); // fixed by tronx2100
```
Comment (eldy) [inline htdocs/includes/odtphp/odf.php:307]: It seems uniqid() is not unique when calling several time fast (see https://www.php.net/manual/fr/function.uniqid.php). 
May be you can call 
`uniqid(mt_rand(), false)`
we do this in a lot of other part of dolibarr code...

**Comment by a-schild** [comment]
Is now updated as recommended. (But with true for more entropy in the uuid(...) call)
