### PR TITLE
FIX(invoice): mutlicurrency_tx correct value

### LINKED ISSUE #32266: Incorrect multicurrency_tx when create invoice from other object
### Bug

When creating invoice from command for example
Multicurrency_tx is not correctly applied. If i set it to 1,08, it will be floor to 1 by int conversion

### Dolibarr Version

20.0.2

### Environment PHP

_No response_

### Environment Database

_No response_

### Steps to reproduce the behavior and expected behavior

- Set Multicurrency to 1,08 or whatever with some digits after comma
- Create a command for a Client with a price at 1080 ot this currency
- From this command, create directly an invoice
- that show you that multicurrency is applied, but when create
- Multicurrency tx is reduce to 1 and invoice prices are reset to 1000, all

### Attached files

_No response_

### PR DESCRIPTION
**Pull request by Slordef**
# FIX #32266 
Instead of taking `originmulticurrency_tx` as an integer, take it from any kind of value to match it correctly

- Fixes #32266

### CODE REVIEW

File: htdocs/compta/facture/card.php [hunk 1]
```diff
@@ -1093,7 +1093,7 @@
 				$object->fk_incoterms       = GETPOSTINT('incoterm_id');
 				$object->location_incoterms = GETPOST('location_incoterms', 'alpha');
 				$object->multicurrency_code = GETPOST('multicurrency_code', 'alpha');
-				$object->multicurrency_tx   = GETPOSTINT('originmulticurrency_tx');
```
Comment (eldy) [inline htdocs/compta/facture/card.php:1096]: Can you use instead GETPOSTFLOAT ?

Comment (Slordef) [reply htdocs/compta/facture/card.php:1096]: Ok, i see that some others values are not right due to "integer" conversion too
I will fix that too in this pr
