### PR TITLE
FIX TCPDI deprecated callables #35194

### LINKED ISSUE #35194: TCPDI deprecated callables
### Bug

We wrote an additional module that modifies an invoice pdf to attach a new page.
If we use PHP 8.1 everything works fine, but as soon as we use php 8.2+ we receive the following warnings:
```
DEPRECATED Callables of the form ["TCPDI", "TCPDF::SetFont"] are deprecated (includes/tcpdi/fpdf_tpl.php:278)
DEPRECATED Callables of the form ["TCPDI", "TCPDF::AddPage"] are deprecated (includes/tcpdi/fpdf_tpl.php:323)
DEPRECATED Callables of the form ["TCPDI", "TCPDF::Image"] are deprecated (includes/tcpdi/fpdf_tpl.php:302)
DEPRECATED Callables of the form ["TCPDI", "TCPDF::Link"] are deprecated (includes/tcpdi/fpdf_tpl.php:338)
```

### Dolibarr Version

22.0.1

### Environment PHP

8.2+

### Environment Database

mariadb 12.0.2

### Steps to reproduce the behavior and expected behavior

we use something like the following code in custom/mymodule/class/actions_mymodule.class.php:
```
...
public function afterPDFCreation($parameters, &$object, &$action) {
...
$outpdf = $parameters['file'];
$pdf = new TCPDI(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
if (class_exists('TCPDF')) {
  $pdf->setPrintHeader(false);
  $pdf->setPrintFooter(false);
}
$pagecount = $pdf->setSourceFile($outpdf);
for ($i = 1; $i <= $pagecount; $i++) {
  $tplidx = $pdf->ImportPage($i);
  $s = $pdf->getTemplateSize($tplidx);
  $pdf->AddPage('P', array($s['w'], $s['h']));
  $pdf->useTemplate($tplidx);
}
$pdf->SetDisplayMode("real", "continuous");
$pdf->SetMargins(0, 0, 0);
$pdf->SetHeaderMargin(0);
$pdf->SetFooterMargin(0);
$pdf->SetAutoPageBreak(false, 0);
$pdf->AddPage($x, $y);
$pdf->AddFont($fonta);
$pdf->AddFont($fontb);
$pdf->SetFont($fonta, '', $default_font_size);
$pdf->Image($conf->$element->dir_output . '/' . $filereference . '/image.png', $xpos, $ypos + 7 + 5, 46, 46, 'PNG', '', '', true, 300, '', false, false, 0, false, false, false);
...
```

### Attached files

_No response_

### PR DESCRIPTION
**Pull request by PsyCrow-code**
FIX #35194 TCPDI deprecated callables
PHP 8.1+ deprecates the sintaxis of callables ["Class", "Class::method"]
Upgraded sintaxis fixes PHP Warnings

CLOSE #35194

### CODE REVIEW

File: htdocs/includes/tcpdi/fpdf_tpl.php [hunk 1]
```diff
@@ -145,7 +145,7 @@ function beginTemplate($x = null, $y = null, $w = null, $h = null) {
     function endTemplate() {
         if (is_subclass_of($this, 'TCPDF')) {
             $args = func_get_args();
-            return call_user_func_array(array($this, 'TCPDF::endTemplate'), $args);
+			return parent::endTemplate(...$args);
```
Comment (eldy) [inline htdocs/includes/tcpdi/fpdf_tpl.php:148]: Does this still work on php 7.1 ?  7.2 ? What is minimal PHP version for this ?

Comment (PsyCrow-code) [reply htdocs/includes/tcpdi/fpdf_tpl.php:148]: Yes, the minimal php version for this sintaxis is 5.6
