### PR TITLE
FIX #30120

### LINKED ISSUE #30120: Setup Default values doesn't work on all pages
### Bug

Hi,

Trying to use "[Default values/filters/sorting](https://wiki.dolibarr.org/index.php?title=Setup_Default_values/filters/sorting)" function I met some issues ...

Apparently, it doesn't not work on some pages. For example, invoice is ok, not project or proposal :

image

Regards 

### Dolibarr Version

18.0.4 & 19.0.2

### Environment PHP

_No response_

### Environment Database

_No response_

### Steps to reproduce the behavior and expected behavior

_No response_

### Attached files

_No response_

### PR DESCRIPTION
**Pull request by zahwyrix**
FIX #30120

### CODE REVIEW

File: htdocs/comm/propal/card.php [hunk 1]
```diff
@@ -1793,6 +1793,7 @@
 	$deposit_percent = GETPOST('cond_reglement_id_deposit_percent', 'alpha');
 	$mode_reglement_id = GETPOSTINT('mode_reglement_id');
 	$fk_account = GETPOSTINT('fk_account');
+	$datepropal = (empty($datepropal) ? (!getDolGlobalString('MAIN_AUTOFILL_DATE') ? -1 : '') : $datepropal);
```
Comment (eldy) [inline htdocs/comm/propal/card.php:1796]: MAIN_AUTOFILL_DATE was introduced for "payment".
You can use MAIN_AUTOFILL_DATE_PROPOSAL
