### PR TITLE
Fix titles in contact pages

### LINKED ISSUE #29098: Contact pages does not set correct browser title
### Bug

Contact pages does not set correct browser title, where as the thirdparty pages (mostly) does set the correct title.

### Dolibarr Version

19.0.0

### Environment PHP

 8.2.7

### Environment Database

 11.3.2-MariaDB-1:11.3.2+maria~ubu2204

### Steps to reproduce the behavior and expected behavior

Create thirdparty. Create contact for thirdparty. Find a list of contacts either all of them, or under thirdparty and contacts.

Then go through all the tabs in the top:

- Contact/Address, page title in browser is New Contact/Address - where's the new coming from?
- Personal data, page title in browser is Contacts/Addresses, should be Personal data
- Related Items, page title in browser is Contacts/Addresses, should be Related items
- Note, page title in browser is Contacts/Addresses, should be Note
- Linked files, page title in browser is Contact Label, should be Linked Files
- Events/Agenda, page title in browser is Contacts/Addresses, should be Events/Agenda

This one is as expected
- Projects, page title in browser is projects, should be projects

### Attached files

contact_event_agenda
contact_linked_files
contact_note
contact_related_items
contact,address_should_be_personal_data
contact_projects
new_contact_should_just_be_contact

### PR DESCRIPTION
**Pull request by bos4711**
FIX #29098

### CODE REVIEW

File: htdocs/contact/card.php [hunk 1]
```diff
@@ -574,7 +574,6 @@
 	$title = $object->lastname;
 }
 $help_url = 'EN:Module_Third_Parties|FR:Module_Tiers|ES:Empresas';
-$title = (getDolGlobalString('SOCIETE_ADDRESSES_MANAGEMENT') ? $langs->trans("NewContact") : $langs->trans("NewContactAddress"));
```
Comment (eldy) [inline htdocs/contact/card.php:577]: Why removing the specialized title used when SOCIETE_ADDRESSES_MANAGEMENT is set ?
