### PR TITLE
FIX #21518

### LINKED ISSUE #21518: When uploading a new logo for third party, old logo files are not deleted from disk
### Bug

Dolibarr 15.0

File system for a third party before uploading new logo:

>./documents/societe/711/logos/logo-ab-horizontal.png
./documents/societe/711/logos/thumbs/logo-ab-horizontal_small.png
./documents/societe/711/logos/thumbs/logo-ab-horizontal_mini.png

Then we upload a new logo named "logo-ab-horizontal2.png" to the same third party:

>./documents/societe/711/logos/logo-ab-horizontal.png
./documents/societe/711/logos/thumbs/logo-ab-horizontal_small.png
./documents/societe/711/logos/thumbs/logo-ab-horizontal_mini.png
./documents/societe/711/logos/thumbs/logo-ab-horizontal2_small.png
./documents/societe/711/logos/thumbs/logo-ab-horizontal2_mini.png
./documents/societe/711/logos/logo-ab-horizontal2.png

Now both logo files exist on disk while only one of them is in use, making the old logo orphaned and waste disk space for no reason.

### Environment Version

15.0.0

### Environment OS

Linux 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Environment Web server

_No response_

### Environment PHP

7.4.30

### Environment Database

_No response_

### Environment URL(s)

_No response_

### Expected and actual behavior

Expected behaviour is that when uploading a new logo, Dolibarr should delete all references (including disk files) to the old logo.

### Steps to reproduce the behavior

_No response_

### Attached files

_No response_

### PR DESCRIPTION
**Pull request by emheyarssi**
Old logo files are not deleted from disk when load a new logo

### CODE REVIEW

File: htdocs/societe/card.php [hunk 1]
```diff
@@ -554,9 +554,8 @@
 			}
 			//var_dump($object->array_languages);exit;
 
-			if (GETPOST('deletephoto')) {
```
Comment (eldy) [inline htdocs/societe/card.php:557]: You must keep the code in this if, used to delete the logo without uploading another one.

Comment (emheyarssi) [reply htdocs/societe/card.php:557]: I'm surprised, according to my tests, this part of code is not necessary.

Comment (emheyarssi) [reply htdocs/societe/card.php:557]: At 780, we delete only if $object->logo != '' but at line 557 (the code you mentioned above I've deleted) we remove de content of $object->logo. So the code at 780 is never executed.
