### PR TITLE
FIX #34893

### LINKED ISSUE #34893: Change password without rights
### Bug

If a user don't have rights to change his password, he can bypass this right with the "password lost" feature.

### Dolibarr Version

all versions

### Environment PHP

any

### Environment Database

_No response_

### Steps to reproduce the behavior and expected behavior

just logout and ask for a new password

### Attached files

_No response_

### PR DESCRIPTION
**Pull request by hregis**
@eldy same bug in all versions

### CODE REVIEW

File: htdocs/user/passwordforgotten.php [hunk 1]
```diff
@@ -131,6 +131,15 @@
 				$result = $edituser->fetch('', '', '', 1, $conf->entity, $username);
 			}
 
+			// If the user does not have the right to change his own password
+			if ($result > 0) {
+				$edituser->getrights('user');
+				if (!$edituser->hasRight('user', 'self', 'password')) {
+					$result = 0;
+					$edituser->error = 'USERNOTFOUND';
```
Comment (eldy) [inline htdocs/user/passwordforgotten.php:139]: May be we can use a different error code like 'USERNOTALLOWEDTOCHANGEPASS'  ?

Comment (hregis) [reply htdocs/user/passwordforgotten.php]: @eldy ready
