### PR TITLE
Fix the remainder to pay amount (#6486)

### LINKED ISSUE #6486: The remainder to pay amount is always equal to 0 in a supplier invoice
# Bug
The remainder to pay amount is always equal to 0 in a supplier invoice card.

## Environment
- **Version**: 5.0
- **OS**: CentOS 7
- **Web server**: apache 2.4
- **PHP**: 5.6
- **Database**: mariadb
- **URL(s)**: fourn/facture/card.php?facid=1

### PR DESCRIPTION
**Pull request by tarrsalah**
The commit fix the remainder to pay amount (`$restapayer` value) in a
supplier invoice card.

# Fix #6486

### CODE REVIEW

File: htdocs/fourn/facture/card.php [hunk 1]
```diff
@@ -2411,6 +2411,8 @@
 				print $langs->trans('AlreadyPaid');
 			print ' :</td><td align="right"'.(($totalpaye > 0)?' class="amountalreadypaid"':'').'>' . price($totalpaye) . '</td><td>&nbsp;</td></tr>';
 
+            $totalpaye = $object->getSommePaiement();
```
Comment (eldy) [inline htdocs/fourn/facture/card.php]: The line just before use $totalpaye. I think this line should be moved up, shouldn't it ?

Comment (tarrsalah) [reply htdocs/fourn/facture/card.php]: I think The the `  $totalpaye = $object->getSommePaiement();` should be removed because we already have `$totalpaye` calculated  in the [loop](https://github.com/tarrsalah/dolibarr/blob/840408c1d21f6895c821b78c62a7bd7090c461aa/htdocs/fourn/facture/card.php#L2375) above.

**Comment by tarrsalah** [comment]
Hello @eldy, is this PR ready to merge, or not yet?
