### PR TITLE
FIX #28347 FIX #28962 FIX #29224  FIX #29035 

### LINKED ISSUE #28347: sales order to p.o.
### Bug

By creating a purchase order from a sales order, even if the purchase prices are correctly entered, the purchase order reflects the sales prices.

### Environment Version

19.0.0

### Environment OS

Linux

### Environment Web server

Litespeed

### Environment PHP

8.2

### Environment Database

_No response_

### Environment URL(s)

_No response_

### Expected and actual behavior

the purchase order should show the purchase prices for that specific supplier, as entered in the product sheet

### Steps to reproduce the behavior

_No response_

### Attached files

_No response_

### LINKED ISSUE #28962: Converting Customer Order to Supplier Order Uses Selling Price Instead of Buying Price
### Bug

Problem Description

When converting a customer order into a supplier order, the product prices are incorrectly taken from the selling prices instead of the buying prices.

Expected Behavior
The prices of the products in the supplier order should be their buying prices.

### Dolibarr Version

19

### Environment PHP

8

### Environment Database

_No response_

### Steps to reproduce the behavior and expected behavior

- Navigate to a customer order.
- Click on "Create" then "Create purchase order".
- Notice that the product prices in the supplier order correspond to the selling prices, not the buying prices.

### Attached files

_No response_

### LINKED ISSUE #29035: Converting customer order to supplier order, customers payment terms are used instead of supplier terms
### Bug

When converting a customer order to a supplier order the payment terms are incorrect. The payment terms of the customer are used insted of the payment terms of the supplier.

### Dolibarr Version

19.0.1 running on Windows11

### Environment PHP

7.3.33

### Environment Database

mariadb 10.6.5

### Steps to reproduce the behavior and expected behavior

- Navigate to customer order
- Create a supplier order out of the customer order
- After the supplier order is generated you can see the wrong payment terms.

### Attached files

_No response_

### LINKED ISSUE #29224: Create Purchase order from Selling order is using sell prices in Purchase order
### Bug

When creating "Purchase order" from "Selling order" (a new function I haven't seen before) the purchase order is using the prices from the selling order, and must be adjusted manually. The Purchase prices should of course be used. Also the discount used in the Selling order is transferred to the Purchase order.

### Dolibarr Version

19.0.1

### Environment PHP

7.4

### Environment Database

_No response_

### Steps to reproduce the behavior and expected behavior

_No response_

### Attached files

_No response_

### PR DESCRIPTION
**Pull request by sonikf**
This feature is currently quite broken, first try to remedy.
Also in #29035 payment terms and other client attributes are carried over.

### CODE REVIEW

File: htdocs/fourn/commande/card.php [hunk 1]
```diff
@@ -1361,7 +1385,7 @@
 									$lines[$i]->fk_product > 0 ? $lines[$i]->fk_product : 0,
 									$product_fourn_price_id,
 									$ref_supplier,
-									$lines[$i]->remise_percent,
+									0,     // $lines[$i]->remise_percent must not be carried over from client to vendor
```
Comment (eldy) [inline htdocs/fourn/commande/card.php:1388]: The supplier order can be created from a supplier proposal. In such case, we must keep all information of the proposal. So we must use here 0 only to create supplier order from a customer order.

File: htdocs/fourn/commande/card.php [hunk 2]
```diff
@@ -1333,10 +1334,35 @@
...
+									$result = $productsupplier->find_min_price_product_fournisseur($lines[$i]->fk_product, $lines[$i]->qty, $object->socid);
 									if ($result > 0) {
 										$ref_supplier = $productsupplier->ref_supplier;
 										$product_fourn_price_id = $productsupplier->product_fourn_price_id;
+										// we need supplier subprice
+										foreach ($srcobject->lines as $li) {
+											$sql = 'SELECT price, unitprice, tva_tx, remise_percent, ref_fourn';
+											$sql .= ' FROM '.MAIN_DB_PREFIX.'product_fournisseur_price';
+											$sql .= ' WHERE fk_product = '.((int) $li->fk_product);
+											$sql .= ' AND fk_soc = '.((int) $object->socid);
```
Comment (eldy) [inline htdocs/fourn/commande/card.php:1346]: Can you check if adding here
`$sql .= " AND entity IN ('".getEntity("product_fournisseur_price").")";`
Your fixis still ok (i think we need this for multicompany support)

Comment (sonikf) [reply htdocs/fourn/commande/card.php:1347]: It works!
