### PR TITLE
Fix #20712 - No more empty wrong line added in bookkeeping confirme_create

### LINKED ISSUE #20712: Accountancy - Empty wrong line added in bookkeeping confirme_create mode
### Bug

When adding a new transaction, some empty line can be stored if we change the journal, the date or the piece name after the creation of the transaction but before the validation of the mouvement.

See below

### Environment Version

14.0.5 and develop (at least)

### Environment OS

_No response_

### Environment Web server

_No response_

### Environment PHP

7.4

### Environment Database

_No response_

### Environment URL(s)

/htdocs/accountancy/bookkeeping/card.php

### Expected and actual behavior

_No response_

### Steps to reproduce the behavior

Go to list by account
Click the "+" icon on the upper right of the screen
Choose a journal
Set à piece name
Create the new transaction
Click on the pen icon near the journal code
Look below
Change the journal and click "Modify"
Look below

### Attached files

Screen just after creating the transaction
BugModifyOnCreateConfirm

Try to Edit Journal
BugUpdateOnEditJournal

When Setting Journal empty line is added
BugUpDateOnSetJournal

### PR DESCRIPTION
**Pull request by daraelmin**
# FIX #20712 - No more empty wrong line added in bookkeeping confirme_create

Add (and not modify) on create mode
FixCreatemode

No more pen or modify link on transaction movement during editing mode
FixEditJournal

No more empty line when setting new journal
FixSetJournal

### CODE REVIEW

**Comment by aspangaro** [comment]
Hello @daraelmin ,

I confirm the problem of empty line created during an edit.

You fix seems good with a little correction

File: htdocs/accountancy/bookkeeping/card.php [hunk 1]
```diff
@@ -673,7 +679,33 @@
 						print '<input type="hidden" name="id" value="'.$line->id.'">'."\n";
 						print '<input type="submit" class="button" name="update" value="'.$langs->trans("Update").'">';
 						print '</td>';
+					} elseif (empty($line->numero_compte) || (empty($line->debit) &&empty($line->creit))) {
```
Comment (aspangaro) [inline htdocs/accountancy/bookkeeping/card.php:682]: Maybe "&& empty($line->credit)"

Comment (daraelmin) [reply htdocs/accountancy/bookkeeping/card.php:682]: Okidoki

**Comment by daraelmin** [comment]
@aspangaro fix done as you suggested
