### PR TITLE
FIX the SELECT examine more than MAX_JOIN_SIZE rows #12305

### LINKED ISSUE #12305: The SELECT would examine more than MAX_JOIN_SIZE rows
# Bug

On my limited old shared hosting, the page `/htdocs/accountancy/customer/list.php?mainmenu=accountancy&leftmenu=accountancy_dispatch_customer` runs the following SQL command:

```sql
SELECT f.rowid as facid, f.ref as ref, f.datef, f.type as ftype, l.rowid, l.fk_product, l.description, l.total_ht, l.fk_code_ventilation, l.product_type as type_l, l.tva_tx as tva_tx_line, l.vat_src_code, p.rowid as product_id, p.ref as product_ref, p.label as product_label, p.fk_product_type as type, p.accountancy_code_sell as code_sell, p.tva_tx as tva_tx_prod, p.accountancy_code_sell_intra as code_sell_intra, p.accountancy_code_sell_export as code_sell_export, aa.rowid as aarowid, aa2.rowid as aarowid_intra, aa3.rowid as aarowid_export, co.code as country_code, co.label as country_label, s.tva_intra
FROM llx_facture AS f
INNER JOIN llx_societe AS s
ON s.rowid = f.fk_soc
LEFT JOIN llx_c_country AS co
ON co.rowid = s.fk_pays
INNER JOIN llx_facturedet AS l
ON f.rowid = l.fk_facture
LEFT JOIN llx_product AS p
ON p.rowid = l.fk_product
LEFT JOIN llx_accounting_account AS aa
ON p.accountancy_code_sell = aa.account_number AND aa.active = 1 AND aa.fk_pcg_version = 'PCG99-ABREGE' AND aa.entity = 1
LEFT JOIN llx_accounting_account AS aa2
ON p.accountancy_code_sell_intra = aa2.account_number AND aa2.active = 1 AND aa2.fk_pcg_version = 'PCG99-ABREGE' AND aa2.entity = 1
LEFT JOIN llx_accounting_account AS aa3
ON p.accountancy_code_sell_export = aa3.account_number AND aa3.active = 1 AND aa3.fk_pcg_version = 'PCG99-ABREGE' AND aa3.entity = 1
WHERE f.fk_statut > 0 AND l.fk_code_ventilation <= 0 AND l.product_type <= 2 AND f.type IN(0, 1, 2, 3, 5) AND f.entity IN(1)
ORDER BY f.datef
DESC, f.ref, l.rowid
```

and get the following error message from MySQL database:

**The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay**

The command `SELECT @@MAX_JOIN_SIZE` returns the low value `300000`.

A workaround is to execute `SET SQL_BIG_SELECTS=1` just before.

## Environment
- **Version**: 10.0.2 and 10.0.3
- **OS**: Ubuntu 14.04
- **Web server**: Apache/2.4.10 (Ubuntu)
- **PHP**: 7.2.0
- **Database**: MySQL 5.5.53-0ubuntu0.14.04.1dargor1
- **URL**: /htdocs/accountancy/customer/list.php?mainmenu=accountancy&leftmenu=accountancy_dispatch_customer

## Logs

```
2019-11-02 18:45:20 INFO    88.121.131.141->88.121.131.141 --- Access to /htdocs/accountancy/customer/list.php - action=, massaction=
2019-11-02 18:45:20 DEBUG   88.121.131.141->88.121.131.141 Menubase::menuLoad mymainmenu=accountancy myleftmenu=accountancy_dispatch_customer type_user=0 menu_handler=eldy tabMenu size=0
2019-11-02 18:45:20 DEBUG   88.121.131.141->88.121.131.141 sql=SELECT m.rowid, m.type, m.module, m.fk_menu, m.fk_mainmenu, m.fk_leftmenu, m.url, m.titre, m.langs, m.perms, m.enabled, m.target, m.mainmenu, m.leftmenu, m.position FROM llx_menu as m WHERE m.entity IN (0,1) AND m.menu_handler IN ('eldy','all') AND m.usertype IN (0,2) ORDER BY m.position, m.rowid
2019-11-02 18:45:20 DEBUG   88.121.131.141->88.121.131.141 dol_getIdFromCode (value for field pcg_version from key 1 not found into cache)
2019-11-02 18:45:20 DEBUG   88.121.131.141->88.121.131.141 sql=SELECT pcg_version as valuetoget FROM llx_accounting_system WHERE rowid = '1'
2019-11-02 18:45:20 DEBUG   88.121.131.141->88.121.131.141 sql=SELECT rowid, code, label, nature FROM llx_accounting_journal WHERE entity = 1 AND active = 1 ORDER BY label DESC
2019-11-02 18:45:20 DEBUG   88.121.131.141->88.121.131.141 sql=SELECT f.rowid as facid, f.ref as ref, f.datef, f.type as ftype, l.rowid, l.fk_product, l.description, l.total_ht, l.fk_code_ventilation, l.product_type as type_l, l.tva_tx as tva_tx_line, l.vat_src_code, p.rowid as product_id, p.ref as product_ref, p.label as product_label, p.fk_product_type as type, p.accountancy_code_sell as code_sell, p.tva_tx as tva_tx_prod, p.accountancy_code_sell_intra as code_sell_intra, p.accountancy_code_sell_export as code_sell_export, aa.rowid as aarowid, aa2.rowid as aarowid_intra, aa3.rowid as aarowid_export, co.code as country_code, co.label as country_label, s.tva_intra FROM llx_facture as f INNER JOIN llx_societe as s ON s.rowid = f.fk_soc LEFT JOIN llx_c_country as co ON co.rowid = s.fk_pays  INNER JOIN llx_facturedet as l ON f.rowid = l.fk_facture LEFT JOIN llx_product as p ON p.rowid = l.fk_product LEFT JOIN llx_accounting_account as aa  ON p.accountancy_code_sell = aa.account_number         AND aa.active = 1  AND aa.fk_pcg_version = 'PCG99-ABREGE' AND aa.entity = 1 LEFT JOIN llx_accounting_account as aa2 ON p.accountancy_code_sell_intra = aa2.account_number  AND aa2.active = 1 AND aa2.fk_pcg_version = 'PCG99-ABREGE' AND aa2.entity = 1 LEFT JOIN llx_accounting_account as aa3 ON p.accountancy_code_sell_export = aa3.account_number AND aa3.active = 1 AND aa3.fk_pcg_version = 'PCG99-ABREGE' AND aa3.entity = 1 WHERE f.fk_statut > 0 AND l.fk_code_ventilation <= 0 AND l.product_type <= 2 AND f.type IN (0,1,2,3,5) AND f.entity IN (1) ORDER BY f.datef DESC, f.ref, l.rowid
2019-11-02 18:45:20 ERR     88.121.131.141->88.121.131.141 DoliDBMysqli::query SQL Error message: DB_ERROR_1104 The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay
2019-11-02 18:45:20 DEBUG   88.121.131.141->88.121.131.141 accountancy/customer/list.php
2019-11-02 18:45:20 DEBUG   88.121.131.141->88.121.131.141 sql=SELECT f.rowid as facid, f.ref as ref, f.datef, f.type as ftype, l.rowid, l.fk_product, l.description, l.total_ht, l.fk_code_ventilation, l.product_type as type_l, l.tva_tx as tva_tx_line, l.vat_src_code, p.rowid as product_id, p.ref as product_ref, p.label as product_label, p.fk_product_type as type, p.accountancy_code_sell as code_sell, p.tva_tx as tva_tx_prod, p.accountancy_code_sell_intra as code_sell_intra, p.accountancy_code_sell_export as code_sell_export, aa.rowid as aarowid, aa2.rowid as aarowid_intra, aa3.rowid as aarowid_export, co.code as country_code, co.label as country_label, s.tva_intra FROM llx_facture as f INNER JOIN llx_societe as s ON s.rowid = f.fk_soc LEFT JOIN llx_c_country as co ON co.rowid = s.fk_pays  INNER JOIN llx_facturedet as l ON f.rowid = l.fk_facture LEFT JOIN llx_product as p ON p.rowid = l.fk_product LEFT JOIN llx_accounting_account as aa  ON p.accountancy_code_sell = aa.account_number         AND aa.active = 1  AND aa.fk_pcg_version = 'PCG99-ABREGE' AND aa.entity = 1 LEFT JOIN llx_accounting_account as aa2 ON p.accountancy_code_sell_intra = aa2.account_number  AND aa2.active = 1 AND aa2.fk_pcg_version = 'PCG99-ABREGE' AND aa2.entity = 1 LEFT JOIN llx_accounting_account as aa3 ON p.accountancy_code_sell_export = aa3.account_number AND aa3.active = 1 AND aa3.fk_pcg_version = 'PCG99-ABREGE' AND aa3.entity = 1 WHERE f.fk_statut > 0 AND l.fk_code_ventilation <= 0 AND l.product_type <= 2 AND f.type IN (0,1,2,3,5) AND f.entity IN (1) ORDER BY f.datef DESC, f.ref, l.rowid LIMIT 1001
2019-11-02 18:45:20 ERR     88.121.131.141->88.121.131.141 DoliDBMysqli::query SQL Error message: DB_ERROR_1104 The SELECT would examine more than MAX_JOIN_SIZE rows; check your WHERE and use SET SQL_BIG_SELECTS=1 or SET MAX_JOIN_SIZE=# if the SELECT is okay
2019-11-02 18:45:20 INFO    88.121.131.141->88.121.131.141 --- End access to /htdocs/accountancy/customer/list.php
```

### PR DESCRIPTION
**Pull request by olibre**
# Fix #12305 the SELECT examine more than MAX_JOIN_SIZE rows

Mon [hébergement mutualisé](https://www.online.net/fr/hosting/online-perso) limite `MAX_JOIN_SIZE` :

```sql
SELECT @@MAX_JOIN_SIZE
300000
```

Sur mon ordinateur personnel, j'ai une valeur immense :

```sql
SELECT @@MAX_JOIN_SIZE
18446744073709551615
```

La correction consiste à prévenir MySQL que c'est un gros `SELECT` avec les commandes suivantes :

```php
$db->query("SET SQL_BIG_SELECTS=1");

[... le code du gros SELECT ...]

$db->query("SET SQL_BIG_SELECTS=0");
```

Je n'ai pas testé avec PostgreSQL.

### CODE REVIEW

File: htdocs/accountancy/customer/index.php [hunk 1]
```diff
@@ -140,6 +140,9 @@
 	$sql.= " AND l.product_type <= 2";
 
 	dol_syslog('htdocs/accountancy/customer/index.php');
+	// MAX_JOIN_SIZE can be very low (ex: 300000) on some limited configurations (ex: https://www.online.net/fr/hosting/online-perso)
+	// This big SELECT command may exceed the MAX_JOIN_SIZE limit => Therefore we use SQL_BIG_SELECTS=1 to disable the MAX_JOIN_SIZE security
+	$db->query("SET SQL_BIG_SELECTS=1");
```
Comment (eldy) [inline htdocs/accountancy/customer/index.php]: You should add here a test 
if ($db->type == 'mysqli') so the code will be done only for mysql

**Comment by olibre** [comment]
Thanks for your advice, I have just added the check `if ($db->type == 'mysqli')` :smile: 

I have also removed the unnecessary `SET SQL_BIG_SELECTS=0` in `htdocs/accountancy/customer/index.php`. It still works on my limited shared hosting. I did a `git push --force` to avoid polluting Dolibarr Git history.

I am not expert about SQL, but according my understanding, the statement `SET SQL_BIG_SELECTS=0` after the `SELECT` is not required because `SQL_BIG_SELECTS=1` seems to apply to only one `SELECT`. However, in case of misunderstanding, I prefer to keep it. What do you think?
