### PR TITLE
Fix #16893 #16897 V13 picto UpToDate change to Unpaid sometimes

### LINKED ISSUE #16893: Bug: on adherents page picto UpToDate appears as Expired sometimes
# Bug
Bug: on adherents index.php page picto UpToDate appears as Expired sometimes

## Environment
- **Version**: 13.0.2 / develop
- **PHP**: 7.4.16
- **Database**: MariaDB 5.*
- **URL(s)**: htdocs/adherents/index.php?mainmenu=members&leftmenu=

## Expected and actual behavior
Green picto for UpToDate member should be print to screen

## Steps to reproduce the behavior
Refresh the page multiples times. The numbers don't change but the picto may change sometimes.

## Screenshots - The third column in the first image should be green as in the second one
ErrorLibStatutDolnow
image

### LINKED ISSUE #16897: Bug : Wrong picto for Expired membership when no subscription is needed
# Bug Wrong picto for Expired membership 

## Bug Wrong picto for Expired membership when no subscription is needed
When the adherent type doesn't need subscription the status picto for "Expired" appears to be the one for "UpToDate" (See the penultimate line in the screenshot above)

## Bug Wrong picto for Total Expired membership when no subscription is needed in penultimate adherent type
When the last adherent type doesn't need subscription the status picto for Total "Expired" appears to be the one for "UpToDate" (See the last line in the screenshot above)

## [Attached files](https://help.github.com/articles/issue-attachments) (Screenshots, screencasts, dolibarr.log, debugging Bug : 
image

### PR DESCRIPTION
**Pull request by daraelmin**
#Fix #16893 V13 picto UpToDate change to Unpaid sometimes
As $now is set on the start of the script.
But, the timestamp may change before LibStatut is called at the end.
To avoid this we add 10 second to $now before comparing to dol_now() in LibStatut

#Fix #16897 V13 wrong picto for Expired membership when no subscription is needed
Force picto for Expired membership when no subscription is needed to Waiting (as other)

### CODE REVIEW

File: htdocs/adherents/index.php [hunk 1]
```diff
@@ -431,17 +431,17 @@
...
 	print '<td class="right">'.(isset($MembersResiliated[$key]) && $MembersResiliated[$key] > 0 ? $MembersResiliated[$key] : '').' '.$staticmember->LibStatut(0, $adhtype->subscription, 0, 3).'</td>';
 	print "</tr>\n";
 }
 print '<tr class="liste_total">';
 print '<td class="liste_total">'.$langs->trans("Total").'</td>';
-print '<td class="liste_total right">'.$SommeA.' '.$staticmember->LibStatut(-1, $adhtype->subscription, 0, 3).'</td>';
-print '<td class="liste_total right">'.$SommeB.' '.$staticmember->LibStatut(1, $adhtype->subscription, 0, 3).'</td>';
-print '<td class="liste_total right">'.$SommeC.' '.$staticmember->LibStatut(1, $adhtype->subscription, $now, 3).'</td>';
-print '<td class="liste_total right">'.$SommeD.' '.$staticmember->LibStatut(0, $adhtype->subscription, 0, 3).'</td>';
+print '<td class="liste_total right">'.$SommeA.' '.$staticmember->LibStatut(-1, 1, 0, 3).'</td>';
```
Comment (eldy) [inline htdocs/adherents/index.php:441]: Why replacing 
$adhtype->subscription  with  1
if the typoe of membership does not need a subscription, we should have 0 here;

Comment (daraelmin) [reply htdocs/adherents/index.php:441]: Cause when it doesn't need subscription, libstatus will display it "uptodate" even in the "expired" column. 
Moreover, in this situation, the total is always empty (equals 0) so it is confusing to display twice a picto "uptodate" with différent total.

Comment (daraelmin) [reply htdocs/adherents/index.php:441]: See the penultimate line in the screenshot above

111904891-53e9a980-8a49-11eb-8e83-d2c1de14026c
