### PR TITLE
Fix #29843 warning division by zero

### LINKED ISSUE #29843: Bug: Warning: Division by zero
# Instructions
*This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.*
*Please:*
- *replace the bracket enclosed texts with meaningful information*
- *remove any unused sub-section*

# Bug
[*Short description*]

## Environment
- **Version**: 19.0.2
- **OS**: Linux
- **Web server**: Apache
- **PHP**: fpm-fcgi 7.4.33
- **Database**: MySQL or MariaDB 5.5.5-10.4.25-MariaDB-1:10.4.25+maria~stretch-log
- **URL(s)**: /compta/stats/index.php?leftmenu=accountancy_report&modecompta=BOOKKEEPING

## Expected and actual behavior
If I asked for turnover invoiced : the April month is providing me an error

Warning: Division by zero in /home/clients/75b383e1e32cfcb0a1b615c70a4bac17/erp/compta/stats/index.php on line 465
+INF%

## Steps to reproduce the behavior
When opening the report section for Turnover by customer in accounting menu, choose turnover by customer

### PR DESCRIPTION
**Pull request by Hystepik**
Fix a division by zero

### CODE REVIEW

File: htdocs/compta/stats/index.php [hunk 1]
```diff
@@ -461,7 +461,7 @@
 			//var_dump($annee.' '.$year_end.' '.$mois.' '.$month_end);
 			if ($annee < $year_end || ($annee == $year_end && $mois <= $month_end)) {
 				if ($annee_decalage > $minyear && $case <= $casenow) {
-					if (!empty($cum[$caseprev]) && !empty($cum[$case])) {
+					if (!empty($cum[$caseprev]) && !empty($cum[$case]) && $cum[$caseprev] != 0) {
```
Comment (eldy) [inline htdocs/compta/stats/index.php:464]: The test 
!empty($cum[$caseprev])
is not enough ?

Comment (Hystepik) [reply htdocs/compta/stats/index.php:464]: No it's not because 
if $cum[$caseprev] = "0.0" (case already encountered)  then !empty($cum[$caseprev]) == true
This is due to the "." in the string

if !empty($cum[$case]) == true then the division by zero is done
So the test 
$cum[$caseprev] != 0 is important
