### PR TITLE
Fix #32161 - Payment terms are not taken from thirdparty when proposal is created from project

### LINKED ISSUE #32161: Payment terms are not taken from thirdparty when proposal is created from project
### Bug

Payment terms are not taken from thirdparty when proposal is created from project

### Dolibarr Version

19.0

### Environment PHP

n/a

### Environment Database

n/a

### Steps to reproduce the behavior and expected behavior

1. Create a new Thirdparty and set payment terms to any value
2. Create a new project with this thirdparty
3. Create a new proposal from the project

Bug: Payment terms are empty and not taken from thirdparty.

### Attached files

_No response_

### PR DESCRIPTION
**Pull request by glu000**
FIX#32161
Payment terms are not taken from thirdparty when proposal is created from project

### CODE REVIEW

File: htdocs/comm/propal/card.php [hunk 1]
```diff
@@ -1766,6 +1766,7 @@
 	$fk_account = GETPOST('fk_account', 'int');
 
 	// Load objectsrc
+	$soc = null;
```
Comment (eldy) [inline htdocs/comm/propal/card.php:1769]: $soc is already defined line 1757.
An later the added test 
if (!empty($soc)) {
would become useless.

Comment (glu000) [reply htdocs/comm/propal/card.php]: Thanks, corrected it.
