### PR TITLE
Fix #32158

### LINKED ISSUE #32158: PHP Warning when creating a proposal from project
### Bug

There are sveral PHP warning when creating a proposal from project:

Warning: Undefined variable $objectsrc in /Users/gl/Code/GitHub/doli-priv/htdocs/comm/propal/card.php on line 2090

### Dolibarr Version

19.0

### Environment PHP

8.1

### Environment Database

n/a

### Steps to reproduce the behavior and expected behavior

1. Create a new project
2. Navigate to project overview
3. Press the + button to create a new proposal

### Attached files

_No response_

### PR DESCRIPTION
**Pull request by glu000**
Fix #32158
There are sveral PHP warning when creating a proposal from project:

Warning: Undefined variable $objectsrc in /Users/gl/Code/GitHub/doli-priv/htdocs/comm/propal/card.php on line 2090

### CODE REVIEW

File: htdocs/comm/propal/card.php [hunk 1]
```diff
@@ -1766,6 +1766,7 @@
 	$fk_account = GETPOST('fk_account', 'int');
 
 	// Load objectsrc
+	$objectsrc = NULL;
```
Comment (eldy) [inline htdocs/comm/propal/card.php:1769]: Try to use the syntax
`$objectsrc = null;`

Comment (glu000) [reply htdocs/comm/propal/card.php]: Thanks, corrected it
