### PR TITLE
FIX #11948

### LINKED ISSUE #11948: Bug: Product units translated incorrectly
# Bug
Units of products are translated incorrectly in the product card. Instead of translating them via the code as in the selectUnits() function (i.e. "unit" + code), the label of the unit is translated. A standardized translation would be desirable.

## Environment
- **Version**: 10.0.2

### PR DESCRIPTION
**Pull request by Tim-Otte**
Fix for #11948

### CODE REVIEW

File: htdocs/product/card.php [hunk 1]
```diff
@@ -2099,7 +2099,7 @@
 
 				print '<tr><td>'.$langs->trans('DefaultUnitToShow').'</td><td>';
 				if ($unit !== '') {
-					print $langs->trans($unit);
+					print $unit;
```
Comment (eldy) [inline htdocs/product/card.php:2102]: According to documentation of getLabelOfUnit, the result must then be translated with lang->trans before being rendered.
