### PR TITLE
fix replenish with multicurrency

### LINKED ISSUE #30831: Replenish : does not use multicurrency information
### Bug

When using replenish page (`htdocs/product/stock/replenish.php`), the created supplier order is not in the currency defined for the supplier.

### Dolibarr Version

14.0, 18.0, develop

### Environment PHP

7.4

### Environment Database

_No response_

### Steps to reproduce the behavior and expected behavior

1. setup a DLB instance with multicurrency.
2. setup multicurrency with EUR and USD
3. configure main currency as EUR
4. create a supplier 'PABLO ESCOBAR' whose currency is USD.
5. create a product 'CHAPO' 
    1. define wished stock > 0
    2. create a buy price for supplier PABLO ESCOBAR  labeled in USD
Capture d’écran_2024-09-02_14-48-23

    
6. go to replenish page `htdocs/product/stock/replenish.php`. CHAPO should appear. Chose it and create the supplier order
Capture d’écran_2024-09-02_14-49-08

8. The supplier order is labeled in EUR while it should be in USD.
Capture d’écran_2024-09-02_14-49-38

### Attached files

_No response_

### PR DESCRIPTION
**Pull request by thomas-Ngr**
# FIX #30831

Replenish does not use multicurrency information when creating supplier orders.

### CODE REVIEW

File: htdocs/product/stock/replenish.php [hunk 1]
```diff
@@ -194,15 +194,22 @@
...
+
 						$line->tva_tx = $productsupplier->vatrate_supplier;
 						$line->subprice = $productsupplier->fourn_pu;
 						$line->total_ht = $productsupplier->fourn_pu * $qty;
 						$tva = $line->tva_tx / 100;
 						$line->total_tva = $line->total_ht * $tva;
 						$line->total_ttc = $line->total_ht + $line->total_tva;
 						$line->remise_percent = $productsupplier->remise_percent;
-						$line->ref_fourn = $productsupplier->ref_supplier;
-						$line->type = $productsupplier->type;
```
Comment (thomas-Ngr) [inline htdocs/product/stock/replenish.php:205]: This is just to fix deprecated properties, not related with the core of the PR.

Comment (eldy) [reply htdocs/product/stock/replenish.php:205]: Fixing of deprecated properties must be done into develop only. Can you submit fix with just fix of visible bug ?

Comment (thomas-Ngr) [reply htdocs/product/stock/replenish.php]: @eldy Sure, I just did.
